export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOADING_USER = "LOADING_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const UNAUTH_USER = 'UNAUTH_USER';

